### ISSUE TITLE
Control Panel Code

### ISSUE THREAD

**Issue by forbitel** [nielsfaber/alarmo-card#1]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
- Clear the Code from the panel after long time being inactive to prevent the code from being left pushed in.

 
### Additional info
[some example of how the new functionality should look like]

**Comment by Wesleyl89** [comment]
The code also stays when you arm and disarm it

**Comment by Wesleyl89** [comment]
The code also stays when you have it within a conditional card. For example I have this:
```yaml
type: conditional
conditions:
  - entity: alarm_control_panel.home
    state: disarmed
card:
  type: custom:alarmo-card
  entity: alarm_control_panel.brunel
  keep_keypad_visible: false
  button_scale: 1.5
```

This wil make it dissapear immediately once you entered the code and click 'arm away'. Once you disarm the alarm again it will show up but it still has the code entered. I've checked HA's own alarm panel and this one doesn't do that.
