### ISSUE TITLE
Feature Request: Option to Use Native Code Entry Modal in Alarm Control Card

### ISSUE THREAD

**Issue by Arubinu** [nielsfaber/alarmo-card#102]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
I would like it to be possible to choose to display the numeric keypad or the dialog box as done here: https://github.com/iantrich/restriction-card/pull/115

![Image](https://github.com/user-attachments/assets/2205bfab-a0fe-4ecf-b669-1a8f24089747)

It's much more intuitive, especially on a tablet.

### Additional info
- Directly by pressing an alarm activation/deactivation button.
- Press/click on the input box (optional)

**Comment by Arubinu** [comment]
No one interested in this feature?

**Comment by andrew171b** [comment]
I was hoping for same thing would be nice on my phone and tablets as I have the alarm at the top when armed but it takes up a lot of unnecessary space with the number pad when not using the alarm, but keeping just the top portion without the number pad until press disable would be amazing


![Image](https://github.com/user-attachments/assets/bf382a5f-8617-448a-8c25-f29bd6036a81)

**Comment by Arubinu** [comment]
In the end I put the new Home Assistant tile that supports the keyboard.

![Image](https://github.com/user-attachments/assets/d6728f58-050b-4525-8983-f3009a228fa6)
![Image](https://github.com/user-attachments/assets/23fdc6d5-842d-4200-931d-af8bf31806d7)

```yaml
type: tile
entity: alarm_control_panel.alarmo
state_content: last_changed
vertical: false
show_entity_picture: false
features_position: inline
features:
  - type: alarm-modes
grid_options:
  columns: full
```
